# Jekyll Configuration
title: "Thi Vo's Blog"
email: your-email@example.com
description: >-
  Personal blog of Thi Vo - Developer, Creator, and Tech Enthusiast.
  Sharing thoughts on technology, development, and creative projects.
baseurl: ""
url: "https://rocketeerfly.github.io"
github_username: RocketeerFly

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima
future: true

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Blog settings
permalink: /blog/:year/:month/:day/:title/
paginate: 5
paginate_path: "/blog/page:num/"

# Collections
collections:
  posts:
    output: true
    permalink: /blog/:year/:month/:day/:title/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Thi Vo"

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
